export const products = [
    {
        id: 1,
        name: 'Nomad Pouch',
        href: '#',
        price: '$50',
        availability: 'White and Black',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-01.jpg',
        imageAlt: 'White fabric pouch with white zipper, black zipper pull, and black elastic loop.',
    },
    {
        id: 2,
        name: 'Zip Tote Basket',
        href: '#',
        price: '$140',
        availability: 'Washed Black',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-02.jpg',
        imageAlt: 'Front of tote bag with washed black canvas body, black straps, and tan leather handles and accents.',
    },
    {
        id: 3,
        name: 'Medium Stuff Satchel',
        href: '#',
        price: '$220',
        availability: 'Blue',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-03.jpg',
        imageAlt: 'Front of satchel with blue canvas body, black straps and handle, drawstring top, and front zipper pouch.',
    },
    {
        id: 4,
        name: 'Travel Backpack',
        href: '#',
        price: '$180',
        availability: 'Black',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-04.jpg',
        imageAlt: 'Large black travel backpack with multiple compartments and adjustable straps.',
    },
    {
        id: 5,
        name: 'Leather Journal',
        href: '#',
        price: '$45',
        availability: 'Brown Leather',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-05.jpg',
        imageAlt: 'Leather-bound journal with a wrap-around strap and premium paper.',
    },
    {
        id: 6,
        name: 'Compact Camera Case',
        href: '#',
        price: '$75',
        availability: 'Dark Gray',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-06.jpg',
        imageAlt: 'Dark gray camera case with a detachable shoulder strap and padded interior.',
    },

];


export const productSecond = [
    {
        id: 7,
        name: 'Wool Scarf',
        href: '#',
        price: '$30',
        availability: 'Charcoal Gray',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-07.jpg',
        imageAlt: 'Soft wool scarf in charcoal gray with a fringe finish.',
    },
    {
        id: 8,
        name: 'Laptop Sleeve',
        href: '#',
        price: '$85',
        availability: 'Navy Blue',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-08.jpg',
        imageAlt: 'Navy blue laptop sleeve with protective padding and a zipper closure.',
    },
    {
        id: 9,
        name: 'Messenger Bag',
        href: '#',
        price: '$150',
        availability: 'Olive Green',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-01.jpg',
        imageAlt: 'Messenger bag in olive green with adjustable strap and front buckle closure.',
    },
]